
CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id       BIGINT                                  NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    is_active     BOOLEAN,
    token_version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE buildings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    address    VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_buildings PRIMARY KEY (id)
);

CREATE TABLE apartments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    building_id BIGINT                                  NOT NULL,
    unit_number VARCHAR(255)                            NOT NULL,
    floor       INTEGER,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_apartments PRIMARY KEY (id)
);

CREATE TABLE resident_profiles
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    apartment_id BIGINT                                  NOT NULL,
    moved_in_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_resident_profiles PRIMARY KEY (id)
);

CREATE TABLE building_announcements
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    building_id BIGINT                                  NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    message     TEXT                                    NOT NULL,
    created_by  BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_building_announcements PRIMARY KEY (id)
);

CREATE TABLE issues
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by               BIGINT                                  NOT NULL,
    apartment_id             BIGINT                                  NOT NULL,
    category_id              BIGINT,
    title                    VARCHAR(255)                            NOT NULL,
    description              TEXT,
    status                   VARCHAR(255)                            NOT NULL,
    priority                 VARCHAR(255)                            NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    ai_category_confidence   DOUBLE PRECISION,
    ai_category_reason       TEXT,
    ai_classification_status VARCHAR(32)                             NOT NULL,
    is_archived              BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_issues PRIMARY KEY (id)
);

CREATE TABLE issue_categories
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                    VARCHAR(255)                            NOT NULL,
    description             VARCHAR(255),
    required_specialization VARCHAR(255),
    CONSTRAINT pk_issue_categories PRIMARY KEY (id)
);

CREATE TABLE issue_assignments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issue_id      BIGINT                                  NOT NULL,
    technician_id BIGINT                                  NOT NULL,
    assigned_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_issue_assignments PRIMARY KEY (id)
);

CREATE TABLE issue_status_history
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issue_id   BIGINT                                  NOT NULL,
    old_status VARCHAR(255),
    new_status VARCHAR(255)                            NOT NULL,
    changed_by BIGINT                                  NOT NULL,
    changed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_issue_status_history PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issue_id   BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    content    TEXT                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE attachments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issue_id          BIGINT                                  NOT NULL,
    uploaded_by       BIGINT,
    file_url          VARCHAR(255),
    file_name         VARCHAR(255),
    processing_status VARCHAR(50)                             NOT NULL DEFAULT 'PENDING',
    processing_error  TEXT,
    uploaded_at       TIMESTAMP WITHOUT TIME ZONE,
    processed_at      TIMESTAMP WITHOUT TIME ZONE,
    file_type         VARCHAR(255),
    file_size         BIGINT,
    original_filename VARCHAR(255),
    stored_filename   VARCHAR(255),
    thumbnail_path    VARCHAR(500),
    CONSTRAINT pk_attachments PRIMARY KEY (id)
);

CREATE TABLE work_logs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issue_id      BIGINT                                  NOT NULL,
    technician_id BIGINT                                  NOT NULL,
    description   TEXT                                    NOT NULL,
    hours_spent   DOUBLE PRECISION,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_work_logs PRIMARY KEY (id)
);

CREATE TABLE maintenance_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issue_id     BIGINT                                  NOT NULL,
    requested_by BIGINT                                  NOT NULL,
    description  TEXT,
    requested_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_maintenance_requests PRIMARY KEY (id)
);

CREATE TABLE technician_profiles
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    specialization    VARCHAR(255),
    is_available      BOOLEAN,
    max_active_issues INTEGER                                 NOT NULL DEFAULT 5,
    CONSTRAINT pk_technician_profiles PRIMARY KEY (id)
);

CREATE TABLE ai_classification_logs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issue_id           BIGINT                                  NOT NULL,
    raw_input          TEXT,
    predicted_category VARCHAR(255),
    predicted_priority VARCHAR(255),
    confidence_score   DOUBLE PRECISION,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ai_classification_logs PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    message    TEXT                                    NOT NULL,
    type       VARCHAR(255),
    is_read    BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE audit_logs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    action      VARCHAR(255)                            NOT NULL,
    entity_type VARCHAR(255)                            NOT NULL,
    entity_id   BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE verification_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    used        BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_verification_tokens PRIMARY KEY (id)
);

CREATE TABLE sessions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    token      TEXT                                    NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sessions PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES public.roles (id);

ALTER TABLE issue_categories
    ADD CONSTRAINT uc_issue_categories_name UNIQUE (name);

ALTER TABLE maintenance_requests
    ADD CONSTRAINT uc_maintenance_requests_issue UNIQUE (issue_id);

ALTER TABLE resident_profiles
    ADD CONSTRAINT uc_resident_profiles_user UNIQUE (user_id);

ALTER TABLE technician_profiles
    ADD CONSTRAINT uc_technician_profiles_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE ai_classification_logs
    ADD CONSTRAINT FK_AI_CLASSIFICATION_LOGS_ON_ISSUE FOREIGN KEY (issue_id) REFERENCES issues (id);

ALTER TABLE apartments
    ADD CONSTRAINT FK_APARTMENTS_ON_BUILDING FOREIGN KEY (building_id) REFERENCES buildings (id);

ALTER TABLE attachments
    ADD CONSTRAINT FK_ATTACHMENTS_ON_ISSUE FOREIGN KEY (issue_id) REFERENCES issues (id);

ALTER TABLE attachments
    ADD CONSTRAINT FK_ATTACHMENTS_ON_UPLOADED_BY FOREIGN KEY (uploaded_by) REFERENCES users (id);

ALTER TABLE audit_logs
    ADD CONSTRAINT FK_AUDIT_LOGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE building_announcements
    ADD CONSTRAINT FK_BUILDING_ANNOUNCEMENTS_ON_BUILDING FOREIGN KEY (building_id) REFERENCES buildings (id);

ALTER TABLE building_announcements
    ADD CONSTRAINT FK_BUILDING_ANNOUNCEMENTS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_ISSUE FOREIGN KEY (issue_id) REFERENCES issues (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE issues
    ADD CONSTRAINT FK_ISSUES_ON_APARTMENT FOREIGN KEY (apartment_id) REFERENCES apartments (id);

ALTER TABLE issues
    ADD CONSTRAINT FK_ISSUES_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES issue_categories (id);

ALTER TABLE issues
    ADD CONSTRAINT FK_ISSUES_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE issue_assignments
    ADD CONSTRAINT FK_ISSUE_ASSIGNMENTS_ON_ISSUE FOREIGN KEY (issue_id) REFERENCES issues (id);

ALTER TABLE issue_assignments
    ADD CONSTRAINT FK_ISSUE_ASSIGNMENTS_ON_TECHNICIAN FOREIGN KEY (technician_id) REFERENCES users (id);

ALTER TABLE issue_status_history
    ADD CONSTRAINT FK_ISSUE_STATUS_HISTORY_ON_CHANGED_BY FOREIGN KEY (changed_by) REFERENCES users (id);

ALTER TABLE issue_status_history
    ADD CONSTRAINT FK_ISSUE_STATUS_HISTORY_ON_ISSUE FOREIGN KEY (issue_id) REFERENCES issues (id);

ALTER TABLE maintenance_requests
    ADD CONSTRAINT FK_MAINTENANCE_REQUESTS_ON_ISSUE FOREIGN KEY (issue_id) REFERENCES issues (id);

ALTER TABLE maintenance_requests
    ADD CONSTRAINT FK_MAINTENANCE_REQUESTS_ON_REQUESTED_BY FOREIGN KEY (requested_by) REFERENCES users (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE resident_profiles
    ADD CONSTRAINT FK_RESIDENT_PROFILES_ON_APARTMENT FOREIGN KEY (apartment_id) REFERENCES apartments (id);

ALTER TABLE resident_profiles
    ADD CONSTRAINT FK_RESIDENT_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE technician_profiles
    ADD CONSTRAINT FK_TECHNICIAN_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE sessions
    ADD CONSTRAINT FK_SESSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE work_logs
    ADD CONSTRAINT FK_WORK_LOGS_ON_ISSUE FOREIGN KEY (issue_id) REFERENCES issues (id);

ALTER TABLE work_logs
    ADD CONSTRAINT FK_WORK_LOGS_ON_TECHNICIAN FOREIGN KEY (technician_id) REFERENCES users (id);

ALTER TABLE verification_tokens
    ADD CONSTRAINT uc_verification_tokens_token UNIQUE (token);

ALTER TABLE verification_tokens
    ADD CONSTRAINT fk_verification_tokens_on_user
        FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_issues_created_by ON issues (created_by);
CREATE INDEX idx_issues_status ON issues (status);
CREATE INDEX idx_issues_priority ON issues (priority);
CREATE INDEX idx_issues_category_id ON issues (category_id);
CREATE INDEX idx_issues_apartment_id ON issues (apartment_id);
CREATE INDEX idx_issues_is_archived ON issues (is_archived);
CREATE INDEX idx_issue_assignments_issue_id ON issue_assignments (issue_id);
CREATE INDEX idx_issue_assignments_technician_id ON issue_assignments (technician_id);
CREATE INDEX idx_notifications_user_unread ON notifications (user_id, is_read);
CREATE INDEX idx_building_announcements_building_created_at
    ON building_announcements (building_id, created_at DESC);
CREATE INDEX idx_maintenance_requests_requested_by ON maintenance_requests (requested_by);

