CREATE TABLE public.roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE public.tenants
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) NOT NULL,
    schema_name VARCHAR(255) NOT NULL,
    identifier  VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    is_active   BOOLEAN,
    CONSTRAINT pk_tenants PRIMARY KEY (id)
);

ALTER TABLE public.roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE public.tenants
    ADD CONSTRAINT uc_tenants_identifier UNIQUE (identifier);

ALTER TABLE public.tenants
    ADD CONSTRAINT uc_tenants_schema_name UNIQUE (schema_name);