spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_residential
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/public
spring.flyway.default-schema=public
spring.flyway.schemas=public
spring.flyway.create-schemas=true

app.flyway.tenant-location=classpath:db/migration/tenant

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=elsakrasniqi043@gmail.com
spring.mail.password=kzum bqcv glts mrjd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true