CREATE TABLE public.tenants
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    schema_name VARCHAR(255)                            NOT NULL,
    identifier  VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    is_active   BOOLEAN,
    CONSTRAINT pk_tenants PRIMARY KEY (id)
);

CREATE TABLE public.roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id       BIGINT                                  NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    is_active     BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE sessions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    token      TEXT                                    NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sessions PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE sessions
    ADD CONSTRAINT FK_SESSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES public.roles (id);

ALTER TABLE public.roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE public.tenants
    ADD CONSTRAINT uc_tenants_identifier UNIQUE (identifier);

ALTER TABLE public.tenants
    ADD CONSTRAINT uc_tenants_schema_name UNIQUE (schema_name);